// BDP-2444 / ADR-0152 — ServerStreamEvent union generator (TypeScript half).
//
// Reads src/contract/server-stream-event.schema.json (the standalone JSON-Schema
// document emitted by omnigent's event_schema_document()) and emits
// src/generated/server-stream-events.ts: the 44-variant `ServerStreamEvent`
// discriminated union keyed on the `type` literal, the shared sub-objects the
// variants reference (ResponseObject, Usage, …), an `UnknownEvent` escape hatch,
// the known-discriminator set, and `parseServerStreamEvent(json)` which dispatches
// on `type` and never throws on an unknown frame.
//
// Why a custom generator: openapi-typescript (like NSwag for C#) flattens a
// oneOf+discriminator into a non-discriminated bag — there is no `type`-keyed
// narrowing and `parse` would be hand-written anyway (see codegen/SPIKE.md). This
// tool owns ONLY the event union + its sub-objects; openapi-typescript still owns
// every HTTP DTO in src/contract/openapi.json (a separate output).
//
// Determinism: the schema's $defs and each variant's properties are emitted in
// the order JSON-Schema lists them (the document is produced with sort_keys=True
// upstream), and there are no timestamps, so `regenerate` reproduces byte-for-byte.
// Never hand-edit the output.

import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const sdkRoot = resolve(here, "..");
const schemaPath = join(sdkRoot, "src", "contract", "server-stream-event.schema.json");
const outputPath = join(sdkRoot, "src", "generated", "server-stream-events.ts");

const root = JSON.parse(readFileSync(schemaPath, "utf8"));
const discriminatorProp = root.discriminator.propertyName;
const mapping = root.discriminator.mapping;
const defs = root["$defs"];

// Ordered (typeLiteral, defName) pairs. JSON object key order is preserved by
// JSON.parse for string keys, and the document is canonicalized (sorted keys)
// upstream, so this is deterministic.
const variants = Object.entries(mapping).map(([typeLiteral, ref]) => ({
  typeLiteral,
  defName: ref.split("/").pop(),
}));
const variantDefNames = new Set(variants.map((v) => v.defName));

// Shared sub-objects = every $def that is NOT a discriminator variant, in schema
// order. The variants reference these by name; emit them first so the union types
// resolve. Mirrors the C# split (NSwag owns these for the C# SDK).
const sharedDefs = Object.keys(defs).filter((name) => !variantDefNames.has(name));

let out = "";
out +=
  "// <auto-generated>\n" +
  "//     Generated by codegen/generate-events.mjs from\n" +
  "//     src/contract/server-stream-event.schema.json (BDP-2444, ADR-0152).\n" +
  `//     The ${variants.length}-variant ServerStreamEvent discriminated union plus the shared\n` +
  "//     sub-objects it references. openapi-typescript cannot model the union\n" +
  "//     (see codegen/SPIKE.md); this file is the deterministic generator output.\n" +
  "//     DO NOT EDIT — run `npm run regenerate`.\n" +
  "// </auto-generated>\n" +
  "/* eslint-disable */\n\n";

// ── Shared sub-objects ───────────────────────────────────
out += "// ── Shared sub-objects (referenced by the event variants) ──\n\n";
for (const name of sharedDefs) {
  out += emitInterface(name, defs[name]);
}

// ── Variant interfaces ───────────────────────────────────
out += "// ── Event variants (one per discriminator) ──\n\n";
for (const { typeLiteral, defName } of variants) {
  out += emitVariant(defName, typeLiteral, defs[defName]);
}

// ── The discriminated union ──────────────────────────────
out += "/**\n";
out += ` * Every Omnigent server-stream event, as a discriminated union keyed on the\n`;
out += ` * \`${discriminatorProp}\` literal. There are ${variants.length} variants — \`parseServerStreamEvent\`\n`;
out += ` * narrows by \`${discriminatorProp}\` (every wire \`${discriminatorProp}\` literal has a variant,\n`;
out += ` * enforced by the every-wire-type test).\n`;
out += " */\n";
out += "export type ServerStreamEvent =\n";
out += variants.map((v) => `  | ${v.defName}`).join("\n") + ";\n\n";

// ── UnknownEvent ─────────────────────────────────────────
out +=
  "/**\n" +
  " * A frame whose wire `type` discriminator the SDK's pinned schema does not\n" +
  " * know. The reader yields this (preserving the raw payload) instead of throwing,\n" +
  " * so a newer server event never tears a live stream down — version-skew safety.\n" +
  " * Deliberately NOT part of `ServerStreamEvent`: it is only ever constructed by\n" +
  " * the parser, never matched against the discriminator union.\n" +
  " */\n" +
  "export interface UnknownEvent {\n" +
  '  readonly kind: "unknown";\n' +
  "  /** The wire `type` literal the SDK could not resolve. */\n" +
  "  readonly type: string;\n" +
  "  /** The full decoded JSON payload of the unknown frame. */\n" +
  "  readonly raw: Record<string, unknown>;\n" +
  "}\n\n";

// ── Known-discriminator set ──────────────────────────────
out +=
  "/**\n" +
  " * The set of wire `type` discriminators this generated union knows. Derived\n" +
  " * from the schema's discriminator mapping so it stays in lockstep with\n" +
  " * regeneration (no second hand-maintained list to drift). Used by the reader to\n" +
  " * tell an UNKNOWN discriminator (version skew) apart from a malformed payload\n" +
  " * for a KNOWN type.\n" +
  " */\n" +
  "export const SERVER_STREAM_EVENT_TYPES: ReadonlySet<string> = new Set([\n" +
  variants.map((v) => `  ${JSON.stringify(v.typeLiteral)},`).join("\n") +
  "\n]);\n\n";

// ── parseServerStreamEvent ───────────────────────────────
out +=
  "/**\n" +
  " * Parse a decoded JSON object into a typed `ServerStreamEvent`, dispatching on\n" +
  " * the `type` discriminator. An object whose `type` is not in\n" +
  " * `SERVER_STREAM_EVENT_TYPES` (or which is not an object with a string `type`)\n" +
  " * is surfaced as an `UnknownEvent` — this function never throws on shape, so an\n" +
  " * unknown or skewed server event survives the stream. The runtime shape of a\n" +
  " * known variant is trusted from the pinned contract (no per-field validation,\n" +
  " * matching the C# System.Text.Json polymorphic deserializer).\n" +
  " */\n" +
  "export function parseServerStreamEvent(\n" +
  "  json: unknown,\n" +
  "): ServerStreamEvent | UnknownEvent {\n" +
  "  if (typeof json !== \"object\" || json === null) {\n" +
  '    return { kind: "unknown", type: "", raw: {} };\n' +
  "  }\n" +
  "  const obj = json as Record<string, unknown>;\n" +
  "  const t = obj[" + JSON.stringify(discriminatorProp) + "];\n" +
  "  if (typeof t === \"string\" && SERVER_STREAM_EVENT_TYPES.has(t)) {\n" +
  "    return obj as unknown as ServerStreamEvent;\n" +
  "  }\n" +
  '  return { kind: "unknown", type: typeof t === "string" ? t : "", raw: obj };\n' +
  "}\n";

// Normalize to LF and ensure a single trailing newline for byte-stable output.
let text = out.replace(/\r\n/g, "\n");
if (!text.endsWith("\n")) text += "\n";

mkdirSync(dirname(outputPath), { recursive: true });
writeFileSync(outputPath, text, "utf8");
console.log(`Generated ${variants.length} variants + ${sharedDefs.length} shared sub-objects -> ${outputPath}`);

// ── Emitters ─────────────────────────────────────────────

function emitVariant(defName, typeLiteral, def) {
  const required = new Set(def.required ?? []);
  let s = emitDoc(def.description);
  s += `export interface ${defName} {\n`;
  // The discriminator is a fixed string literal on each variant.
  s += `  ${quoteKey(discriminatorProp)}: ${JSON.stringify(typeLiteral)};\n`;
  for (const [propName, propSchema] of Object.entries(def.properties ?? {})) {
    if (propName === discriminatorProp) continue; // fixed above
    s += emitProperty(propName, propSchema, required.has(propName));
  }
  s += "}\n\n";
  return s;
}

function emitInterface(name, def) {
  const required = new Set(def.required ?? []);
  let s = emitDoc(def.description);
  s += `export interface ${name} {\n`;
  for (const [propName, propSchema] of Object.entries(def.properties ?? {})) {
    s += emitProperty(propName, propSchema, required.has(propName));
  }
  // Open dicts (additionalProperties) carry arbitrary extra keys.
  if (def.additionalProperties && def.additionalProperties !== false) {
    s += "  readonly [extra: string]: unknown;\n";
  }
  s += "}\n\n";
  return s;
}

function emitProperty(propName, propSchema, isRequired) {
  // A C# `null` on a nullable field round-trips as OMITTED (the server uses
  // exclude_none), so optional members are `?:` and never carry `| null` — they
  // are simply absent on the wire. This mirrors the platform-rule contract
  // (null-vs-undefined: read with `key in obj`/optional chaining, not `=== null`).
  const optional = !isRequired;
  const tsType = mapType(propSchema, /*requiredField*/ true);
  const key = quoteKey(propName);
  return `  readonly ${key}${optional ? "?" : ""}: ${tsType};\n`;
}

// JSON-Schema property shape -> TS type. Covers every shape across the 44 variants
// + shared sub-objects (enumerated from the live schema): scalars, anyOf[T,null]
// optionals, $ref to a shared sub-object, arrays of $ref/object, free-form objects.
function mapType(schema, requiredField) {
  // anyOf [X, null] — the Pydantic optional pattern. The non-null branch is the
  // type; the `null` branch is dropped (omitted-on-wire, see emitProperty).
  if (schema.anyOf) {
    let nonNull = null;
    for (const branch of schema.anyOf) {
      if (branch.type === "null") continue;
      nonNull = branch;
    }
    return nonNull ? mapType(nonNull, true) : "Record<string, unknown>";
  }

  if (schema["$ref"]) {
    return schema["$ref"].split("/").pop();
  }

  switch (schema.type) {
    case "string":
      return "string";
    case "integer":
    case "number":
      return "number";
    case "boolean":
      return "boolean";
    case "array": {
      const items = schema.items ?? {};
      const itemType = items["$ref"]
        ? items["$ref"].split("/").pop()
        : items.type === "string"
          ? "string"
          : items.type === "integer" || items.type === "number"
            ? "number"
            : items.type === "boolean"
              ? "boolean"
              : "Record<string, unknown>";
      return `ReadonlyArray<${itemType}>`;
    }
    case "object":
      // free-form object (additionalProperties) -> raw JSON.
      return "Record<string, unknown>";
    default:
      // Unknown shape — surface as raw JSON rather than silently dropping.
      return "Record<string, unknown>";
  }
}

function emitDoc(description) {
  if (typeof description !== "string" || description.length === 0) return "";
  const lines = description.replace(/\r\n/g, "\n").split("\n");
  let s = "/**\n";
  for (const line of lines) {
    s += line.length > 0 ? ` * ${line.replace(/\*\//g, "*\\/")}\n` : " *\n";
  }
  s += " */\n";
  return s;
}

// A TS object-literal key is bare when it's a valid identifier; otherwise quoted.
function quoteKey(name) {
  return /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(name) ? name : JSON.stringify(name);
}
